# ADALINE

In [1]:
# Importing neccessary libraries
import numpy as np

In [2]:
# Predict Function
''' Arguments : Weights id 2D vector (1,number of features + 1) --- +1 indicate bias             
                Input is 1D vector (number_of_features,) 
'''
def predict(Weights,Input):
    ans = np.dot(Input, Weights[0,1:]) + Weights[0,0]
    return ans

In [3]:
''' 
 Signum Function for predicting accurate label
 Because Adaline will give numeric result and that result 
 shud be compared with threshold to decide the correct label
 here threshold is taken as 0.5 as label is 0 and 1
 so predicted values will lie between 0 and 1 
'''
def signum(x):
    threshold = 0.5
    if x >= threshold:
        return 1
    else:
        return 0

In [4]:
# Adaline Training Function
''' Arguments : Input is 2D vector (m,n) where m is number of training example and n is number of features
                Label is 1D vector (m,)
                lr is Learning rate which is initialised with 0.1
                iter is number of iteration which is initialised to 10
'''
def Adaline_Train(Input,Label,lr = 0.01,iter = 100):
    m,n = Input.shape
    # concatenating 1 to features vector for learning bias
    Input = np.hstack((np.ones((m, 1)),Input))
    # Initializing Weights with random value of shape (1,n+1) ..+1 is for bias
    W = np.random.rand(n+1).reshape((1,n+1))
    # for each iteration 
    for i in range(iter):
        # for each training example
        for j in range(m):
            # predicting output for a example
            Pred = np.dot(Input[j],W.T)
            # updating all the weights including bias
            W = W + lr * (Label[j] - Pred) * Input[j]
    return W  

# For OR Dataset

In [5]:
# Preparing input and target for OR
X = [[0,0],[0,1],[1,0],[1,1]]
Y = [0,1,1,1]
# Converting into numpy array
Input = np.array(X)
Label = np.array(Y)

In [6]:
# Training Adaline with OR dataset

W = Adaline_Train( Input , Label )
print("Weights For OR as a dataset:- ")
print(W)

Weights For OR as a dataset:- 
[[0.4057526  0.31695103 0.42238106]]


In [7]:
# Checking for OR inputs
print("********************** OR ***********************")
print("x1 x2  Output")
inputs = np.array([0, 0])
res = signum(predict(W,inputs))
print("0  0   {}".format(res))

inputs = np.array([1, 0])
res = signum(predict(W,inputs))
print("1  0   {}".format(res))

inputs = np.array([0, 1])
res = signum(predict(W,inputs))
print("0  1   {}".format(res))

inputs = np.array([1, 1])
res = signum(predict(W,inputs))
print("1  1   {}".format(res))

********************** OR ***********************
x1 x2  Output
0  0   0
1  0   1
0  1   1
1  1   1


# For AND Dataset

In [8]:
# Preparing input and target for AND
X = [[0,0],[0,1],[1,0],[1,1]]
Y = [0,0,0,1]
# Converting into numpy array
Input = np.array(X)
Label = np.array(Y)

In [9]:
# Training Adaline with AND dataset

W = Adaline_Train( Input , Label ,0.1,10)
print("Weights For AND as a dataset:- ")
print(W)

Weights For AND as a dataset:- 
[[-0.01852431  0.50680045  0.18739587]]


In [10]:
# Checking for AND inputs
print("********************** AND ***********************")

print("x1 x2  Output")
inputs = np.array([0, 0])
res = signum(predict(W,inputs))
print("0  0   {}".format(res))

inputs = np.array([1, 0])
res = signum(predict(W,inputs))
print("1  0   {}".format(res))

inputs = np.array([0, 1])
res = signum(predict(W,inputs))
print("0  1   {}".format(res))

inputs = np.array([1, 1])
res = signum(predict(W,inputs))
print("1  1   {}".format(res))

********************** AND ***********************
x1 x2  Output
0  0   0
1  0   0
0  1   0
1  1   1


In [11]:
'''
 Normalization is done to bring all the values in similar range.
 We need Data in similar range because training model will deviate 
 so much to reach global minimum and it may be possible that it never
 reaches global minimum. So to handle this problem normalization is used.
 Here , I used Min-Max Normalization which will bring the dataset
 in the range [0,1] 
'''
def Normalization(X):
    mn = np.min(X,axis=0)
    mx = np.max(X,axis=0)
    X = (X - mn)/(mx - mn)
    return X

In [12]:
# Taking dataset from sklearn library
from sklearn import datasets
data = datasets.load_iris() # Data has four features and 150 training examples and 3 classes each has 50 example
X = data.data[0:100,0:2]    # Taking 100 example of two classes and two features
Y = data.target[0:100]

X = Normalization(X)       # Normalizing Input Data

In [13]:
# Shuffling the dataset
m,n = X.shape
l = [i for  i in range(0, m)]
# Shuffling the Indexes
np.random.shuffle(l)
# Shuffling the Dataset according to Shuffled indexes
X = X[l]
Y = Y[l]
partition = (int)( 0.7 * m)  # Partition index for dividing into training and testing dataset
# Partitioning into training and testing dataset
X_train = X[0:partition]
Y_train = Y[0:partition]
X_test  = X[partition:m]
Y_test  = Y[partition:m]

In [14]:
# Training Adaline to classify Setosa and versicolor
W = Adaline_Train(X_train,Y_train,0.01,400)
print("Weights For Iris dataset:- ")
print(W)

Weights For Iris dataset:- 
[[ 0.66209123  1.32534033 -1.53226422]]


In [15]:
# Checking the accuracy for test dataset
y_pred = []
m,n = X_test.shape
for i in range(m):
    y_pred.append(signum(predict(W,X_test[i])))
Diff = y_pred - Y_test
c = Diff[Diff == 0]
print("Accuracy : {}".format((float)(len(c)/m)))

Accuracy : 1.0
